import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Image from "next/image";
import myImage from "../public/src/images/pic.png";
import animal from "../public/src/images/animal.png";
import book from "../public/src/images/book.png";
import weather from "../public/src/images/weather.png";
import team from "../public/src/images/team.png";
import note from "../public/src/images/note.png";
import pass from "../public/src/images/pass-gen.png";
import Link from "next/link";
import {
  AiFillTwitterCircle,
  AiFillGithub,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl"> Joseph Cotterell</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text 2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Portfolio
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font font-medium">
              {" "}
              Joseph Cotterell
            </h2>
            <h3 className="text-2xl py-2"> Coding Student</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Hi, my name is Joseph and I am a coding student from Birmingham.
              This is my portfolio where you will find a number of my projects.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16">
            <a href="https://twitter.com/JosephCott1530">
              {" "}
              <AiFillTwitterCircle />{" "}
            </a>
            <a href="https://www.linkedin.com/in/joseph-cotterell-3b1562254/">
              {" "}
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/josephcotterell">
              {" "}
              <AiFillGithub />{" "}
            </a>
          </div>
          <div className="relative mx-auto rounded-full w-80 h-80 mt-20 ">
            <Image src={myImage} layout />
          </div>
        </section>

        <section>
          <div className="text-center p-10">
            <h3 className="text-3xl py-1">About Me</h3>
            <p className="text-md py-1 leading-8 text-gray-800">
              I have been studying coding since October 2022 at Birmingham Uni.
              I am nearing the end of the course and have learnt various
              languages such as: HTML, CSS, JavaScript, MySQL, React etc.
            </p>
          </div>
          <div>
            <div
              div
              className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1"
            >
              <h3 className="text-2xl py-1 ">My Portfolio</h3>
              <h4 className="text-2xl py-1 mt-20 ">Animl</h4>
              <div className="relative mx-auto rounded-full w-80 h-80 mt-20">
                <Link href=" https://github.com/AlastairHafield/Animl-Project">
                  https://github.com/AlastairHafield/Animl-Project
                </Link>
                <Image src={animal} />
              </div>

              <h4 className="text-2xl py-1 mt-20 ">Password Generator</h4>
              <div className="relative mx-auto rounded-full w-80 h-80 mt-20">
                <Link href="https://github.com/josephcotterell/password-generator">
                  https://github.com/josephcotterell/password-generator
                </Link>
                <Image src={pass} />
              </div>
              <h4 className="text-2xl py-1 mt-20 ">Book Nook</h4>
              <div className="relative mx-auto rounded-full w-80 h-80 mt-20">
                <Link href="https://github.com/indiataylor1/book-nook">
                  https://github.com/indiataylor1/book-nook
                </Link>
                <Image src={book} />
              </div>
              <h4 className="text-2xl py-1 mt-20 ">Weather App</h4>
              <div className="relative mx-auto rounded-full w-80 h-80 mt-20">
                <Link href="  https://github.com/josephcotterell/Weather-Dashboard">
                  https://github.com/josephcotterell/Weather-Dashboard
                </Link>
                <Image src={weather} />
              </div>
              <h4 className="text-2xl py-1 mt-20 ">Team Profile Generator</h4>
              <div className="relative mx-auto rounded-full w-80 h-80 mt-20">
                <Link href="https://github.com/josephcotterell/Team-Profile-Gen">
                  {" "}
                  https://github.com/josephcotterell/Team-Profile-Gen{" "}
                </Link>
                <Image src={team} />
              </div>
              <h4 className="text-2xl py-1 mt-20 ">Note Taker</h4>
              <div className="relative mx-auto rounded-full w-80 h-80 mt-20">
                <Link href="https://github.com/josephcotterell/Note-Taker">
                  https://github.com/josephcotterell/Note-Taker
                </Link>
                <Image src={note} />
              </div>

              <div>
                <h3>Contact</h3>
                <h4>Email: josephcotterell@hotmail.co.uk</h4>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
